services:
  frontend:
    image: yunn0123/nail-it-frontend:${VERSION_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GITHUB_SHA=${GITHUB_SHA:-local}
        - VERSION=${VERSION_TAG:-local}
        - ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
      - VERSION=${VERSION_TAG:-local}
    depends_on:
      - backend
    restart: always
 
  backend:
    image: yunn0123/nail-it-backend:${VERSION_TAG:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - GITHUB_SHA=${GITHUB_SHA:-local}
        - VERSION=${VERSION_TAG:-local}
        - ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "5001:5000"
    environment:
      # - {database}
      - PORT=5000
      - VERSION=${VERSION_TAG:-local}
    # 移除依賴，因為我們目前不使用任何數據庫
    # depends_on:
    #   - supabase
    restart: always
  
  # 註釋掉Supabase服務，未來需要時再取消註釋
  # supabase:
  #   image: supabase/postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: nailit
  #   volumes:
  #     - supabase-data:/var/lib/postgresql/data
  #   restart: always
    
# 在Railway上定義的卷 - 註釋掉，因為目前不需要
# volumes:
#   supabase-data:
#     # 此處不需要配置，Railway會自動管理