version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # 對外 3000，內部 5173 (Vite 開發端口)
    restart: always
    environment:
      - VITE_BACKEND_API_URL=http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # 避免覆蓋 node_modules
      
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=4000
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - ./backend/nail-resv:/app
      - /app/node_modules  # 避免覆蓋 node_modules
      - ./backend/nail-resv/uploads:/app/uploads  # 持久化上傳檔案
