version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    environment:
      - VERSION=latest
      - ENVIRONMENT=production

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5001:5000"
  #   restart: always
  #   environment:
  #     - PORT=5000
  #     - VERSION=latest
  #     - ENVIRONMENT=production