services:
  frontend:
    image: yunn0123/nail-it-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GITHUB_SHA: local
        VERSION: latest
        ENVIRONMENT: production
        BUILD_DATE: "20250523000000"  # 固定時間戳
    ports:
      - "80:80"  # 修改為標準 HTTP 端口，與 Nginx 配置一致
    environment:
      - VERSION=latest
    # 移除 volumes 設置，使用 Railway Volumes 代替
    # volumes:
    #   - ./frontend/src:/app/src:ro
    restart: always
 
  # 暫時註釋掉後端服務以僅運行前端
  # backend:
  #   image: yunn0123/nail-it-backend:${VERSION_TAG:-latest}
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     args:
  #       GITHUB_SHA: local
  #       VERSION: latest
  #       ENVIRONMENT: production
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     # - {database}
  #     - PORT=5000
  #     - VERSION=latest
  #   # 移除依賴，因為我們目前不使用任何數據庫
  #   # depends_on:
  #   #   - supabase
  #   restart: always
  
  # 註釋掉Supabase服務，未來需要時再取消註釋
  # supabase:
  #   image: supabase/postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: nailit
  #   volumes:
  #     - supabase-data:/var/lib/postgresql/data
  #   restart: always
    
# 在Railway上定義的卷 - 註釋掉，因為目前不需要
# volumes:
#   supabase-data:
#     # 此處不需要配置，Railway會自動管理