services:
  frontend:
    image: yunn0123/nail-it-frontend:${VERSION_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GITHUB_SHA: ${GITHUB_SHA:-local}
        VERSION: ${VERSION_TAG:-local}
        ENVIRONMENT: ${ENVIRONMENT:-development}
        BUILD_DATE: "$(date +%Y%m%d%H%M%S)"  # 添加時間戳參數破壞緩存
    ports:
      - "80:80"  # 修改為標準 HTTP 端口，與 Nginx 配置一致
    environment:
      - VERSION=${VERSION_TAG:-local}
    volumes:
      - ./frontend/src:/app/src:ro  # 只讀掛載源碼以便調試 (不影響容器內部的構建)
    restart: always
 
  # 暫時註釋掉後端服務以僅運行前端
  # backend:
  #   image: yunn0123/nail-it-backend:${VERSION_TAG:-latest}
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     args:
  #       - GITHUB_SHA=${GITHUB_SHA:-local}
        - VERSION=${VERSION_TAG:-local}
        - ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "5001:5000"
    environment:
      # - {database}
      - PORT=5000
      - VERSION=${VERSION_TAG:-local}
    # 移除依賴，因為我們目前不使用任何數據庫
    # depends_on:
    #   - supabase
    restart: always
  
  # 註釋掉Supabase服務，未來需要時再取消註釋
  # supabase:
  #   image: supabase/postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: nailit
  #   volumes:
  #     - supabase-data:/var/lib/postgresql/data
  #   restart: always
    
# 在Railway上定義的卷 - 註釋掉，因為目前不需要
# volumes:
#   supabase-data:
#     # 此處不需要配置，Railway會自動管理