name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build-and-deploy:
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Test Docker Hub Authentication
        run: |
          echo "Testing Docker Hub authentication..."
          docker info
          echo "Authentication successful!"
      
      - name: Get Version
        id: get_version
        run: |
          PR_NUMBER=${{ github.event.pull_request.number || 'main' }}
          SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "VERSION=v-${PR_NUMBER:-main}-${SHA}-${TIMESTAMP}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ env.VERSION }}" >> $GITHUB_OUTPUT
      
      # 前端映像建置和推送
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          # 禁用緩存，確保每次都使用最新代碼
          no-cache: true
          tags: |
            yunn0123/nail-it-frontend:latest
            yunn0123/nail-it-frontend:${{ env.VERSION }}
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            VERSION=${{ env.VERSION }}
            ENVIRONMENT=${{ github.event_name == 'pull_request' && 'pr' || 'production' }}
            BUILD_DATE=$(date +%Y%m%d%H%M%S)
      
      # 安裝 Railway CLI 並設置環境
      - name: Install Railway CLI
        run: |
          echo "安裝 Railway CLI..."
          npm install -g @railway/cli@latest
          echo "Railway CLI 版本: $(railway --version)"
      
      # 使用 Railway 部署
      - name: Deploy to Railway
        run: |
          echo "部署到 Railway..."
          echo "使用服務 ID 直接部署，不需要先連接專案"
          export CI=true
          
          # 設置構建日期
          BUILD_DATE=$(date +%Y%m%d%H%M%S)
          echo "BUILD_DATE=$BUILD_DATE"
          
          # 使用 --service 參數直接部署特定服務
          # 注意：將 "nail-it-app" 替換為您的實際服務 ID
          railway up --service=nail-it-app --detach
          
          echo "部署請求已提交，等待部署完成..."
          sleep 10
          railway status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
  cleanup-pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest
      
      - name: Cleanup PR Environment
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "清理 PR #${PR_NUMBER} 環境"
          
          export CI=true
          # 注意：將 "nail-it-app-pr" 替換為您的實際服務命名方式
          # 目前先註釋掉，需要時可以啟用
          # railway service delete --confirm --service=nail-it-app-pr-${PR_NUMBER}
          
          echo "PR 環境清理完成"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
