name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build-and-deploy:
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Test Docker Hub Authentication
        run: |
          echo "Testing Docker Hub authentication..."
          docker info
          echo "Authentication successful!"
      
      - name: Get Version
        id: get_version
        run: |
          PR_NUMBER=${{ github.event.pull_request.number || 'main' }}
          SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "VERSION=v-${PR_NUMBER:-main}-${SHA}-${TIMESTAMP}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ env.VERSION }}" >> $GITHUB_OUTPUT
      
      # 前端映像建置和推送
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          # 禁用緩存，確保每次都使用最新代碼
          no-cache: true
          tags: |
            yunn0123/nail-it-frontend:latest
            yunn0123/nail-it-frontend:${{ env.VERSION }}
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            VERSION=${{ env.VERSION }}
            ENVIRONMENT=${{ github.event_name == 'pull_request' && 'pr' || 'production' }}
            BUILD_DATE=$(date +%Y%m%d%H%M%S)
            # Supabase相關參數 - 目前先註釋掉
            # SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            # SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      # 後端映像建置和推送 - 暫時註釋掉以僅測試前端
      # - name: Build and Push Backend Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./backend
      #     file: ./backend/Dockerfile
      #     push: true
      #     tags: |
      #       yunn0123/nail-it-backend:latest
      #       yunn0123/nail-it-backend:${{ env.VERSION }}
      #     build-args: |
      #       GITHUB_SHA=${{ github.sha }}
      #       VERSION=${{ env.VERSION }}
      #       ENVIRONMENT=${{ github.event_name == 'pull_request' && 'pr' || 'production' }}
      #       # Supabase相關參數 - 目前先註釋掉
      #       # SUPABASE_URL=${{ secrets.SUPABASE_URL }}
      #       # SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: |
          # 使用Railway CLI登入 (通過環境變數)
          # Railway CLI會自動使用RAILWAY_TOKEN環境變數進行認證
          
          # 設置項目和環境
          railway link -p debd9c55-da98-4f2e-9871-197b8b08220d
          
          # 添加卷（如果需要）- 目前只建立uploads卷用於靜態文件存儲
          if ! railway volume list | grep -q "uploads"; then
            railway volume add uploads --mountPath=/app/uploads
            echo "Created uploads volume"
          fi
          
          # 暫時不創建資料庫相關的卷
          # if ! railway volume list | grep -q "supabase-data"; then
          #   railway volume add supabase-data --mountPath=/var/lib/postgresql/data
          #   echo "Created supabase-data volume"
          # fi
          
          # 設置環境變數 - 設置版本號和構建日期
          echo "Setting VERSION=${{ env.VERSION }}"
          railway variables set VERSION=${{ env.VERSION }}
          railway variables set BUILD_DATE=$(date +%Y%m%d%H%M%S)
          
          # 部署應用 - 強制使用最新映像
          echo "Deploying to Railway..."
          railway up --force --detach
          
          # 等待部署完成
          echo "Waiting for deployment to complete..."
          railway service list --json | jq -r '.[].deployments[0].status'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
  cleanup-pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Cleanup PR Environment
        run: |
          # 使用Railway CLI登入 (通過環境變數)
          # Railway CLI會自動使用RAILWAY_TOKEN環境變數進行認證
          
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Cleaning up PR #${PR_NUMBER} environment"
          
          # 根據PR號碼刪除或清理環境 - 目前先註釋掉
          # railway environment delete pr-${PR_NUMBER}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
